[database]
# Type : memory or mysql (default memory)
type = "mysql"
user = "user"
port = 3306
host = "localhost"
pass = "password"
dbname = "booster-web"

[runners]
# galaxy or local. If galaxy: requires galaxykey & galaxyurl
type="galaxy"
galaxykey="apikey"
galaxyurl="http(s)://ip:port"
# Maximum number of pending jobs (default : 10): for galaxy & local
queuesize = 200
# Number of parallel running jobs (default : 1): for local only
nbrunners  = 2
# Number of cpus per bootstrap job : for local only
jobthreads  = 5
# Timout for each job in seconds (default unlimited): for local only
timeout  = 10

[logging]
# Log file : "stdout", "stderr", or any file
logfile = "/var/log/booster.log"

[http]
# HTTP server Listening port
port = 8080
