[[constraint]]
  name = "github.com/dgrijalva/jwt-go"
  version = "3.1.0"

[[constraint]]
  branch = "master"
  name = "github.com/elazarl/go-bindata-assetfs"

[[constraint]]
  name = "github.com/fredericlemoine/goalign"
  version = "0.2.5"

[[constraint]]
  name = "github.com/fredericlemoine/golaxy"
  version = "v0.1.0"

[[constraint]]
  name = "github.com/fredericlemoine/gotree"
  version = "v0.2.6"
  
[[constraint]]
  name = "github.com/go-sql-driver/mysql"
  version = "1.3.0"

[[constraint]]
  branch = "master"
  name = "github.com/nu7hatch/gouuid"

[[constraint]]
  name = "github.com/russross/blackfriday"
  version = "1.5"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.1"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "1.0.0"
